// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-9MYW3yJCFRl3tzn9hgaifXtNKpei_Nk',
    appId: '1:299226866296:web:e894f992510fa5a425c38d',
    messagingSenderId: '299226866296',
    projectId: 'hansungmarketback',
    authDomain: 'hansungmarketback.firebaseapp.com',
    storageBucket: 'hansungmarketback.firebasestorage.app',
    measurementId: 'G-YY2RNSCCFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA0KJbaDH4MobJvkmhwYeAslpkIfJ-GNs',
    appId: '1:299226866296:android:4faaa0cb3aab0bf525c38d',
    messagingSenderId: '299226866296',
    projectId: 'hansungmarketback',
    storageBucket: 'hansungmarketback.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVw7uXwXUoAt0qRLTtSXhZM2Zh3vMO9SY',
    appId: '1:299226866296:ios:42fc53416c794b9d25c38d',
    messagingSenderId: '299226866296',
    projectId: 'hansungmarketback',
    storageBucket: 'hansungmarketback.firebasestorage.app',
    iosBundleId: 'com.example.mobilep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-9MYW3yJCFRl3tzn9hgaifXtNKpei_Nk',
    appId: '1:299226866296:web:55983fce846cda2725c38d',
    messagingSenderId: '299226866296',
    projectId: 'hansungmarketback',
    authDomain: 'hansungmarketback.firebaseapp.com',
    storageBucket: 'hansungmarketback.firebasestorage.app',
    measurementId: 'G-2MH7ZZRN70',
  );
}
